### ISSUE TITLE
hwcomposer: dmabuf modifiers are ignored

### ISSUE THREAD

**Issue by technobaboo** [waydroid/android_hardware_waydroid#51]
According to a Smithay developer (drakulix) helping me with debugging why waydroid was submitting an external dmabuf when I requested from my compositor only non-external ones:

Essentially their hwcomposer needs to save modifiers.
And then their gralloc implementation has not to use gbm_bo_create: https://github.com/waydroid/android_hardware_waydroid/blob/5e8b245543d531e13025ad2ecde0fcbceff27027/gralloc/gralloc_gbm.cpp#L244
But gbm_bo_create_with_modifiers and be given the list of supported modifiers for the format from the wayland code.
That way gbm will not return a buffer with a potentially external modifier.

I don't know how to build this project or I'd do the patch myself.

**Comment by aleasto** [comment]
On my intel machine running kwin_wayland i get `0x0,0x100000000000001,0x100000000000002,0x100000000000004` from zwp_linux_dmabuf_v1 (version 3)

passing the same array to `gbm_bo_create_with_modifiers2`, sometimes the operation fails (that should be when GBM_BO_USE_LINEAR is set as usage flag so we fallback to gbm_bo_create), and when it succeeds it picks `0x100000000000004` which should be `I915_FORMAT_MOD_Y_TILED_CCS` however then `gbm_bo_import` fails.

Without explicit modifiers `0x100000000000002` gets picked, which should be `I915_FORMAT_MOD_Y_TILED`, and everything works

**Comment by aleasto** [comment]
Tentative patch is here https://github.com/waydroid/android_hardware_waydroid/pull/52

**Comment by aleasto** [comment]
Ah well, that's because the `I915_FORMAT_MOD_Y_TILED_CCS` modifier uses two planes. And the same thing happens on my amdgpu device.

Unfortunatly gralloc.gbm does not support multi-planar buffers. We should be able to do this with the new gralloc from [minigbm](https://github.com/waydroid/android_external_minigbm) though (edit: no, we can't).

EDIT: Well, there's also the fact that our hwcomposer does not support multi-planar buffers... I guess for an initial pass we could look into filtering the modifiers to only those that do not add any more planes.
